注意:
	前提:父类中要被重写的方法中没有抛出异常
	当子类实现父类中方法的时候,在实现过程中如果出现“编译时异常”时，只能通过try...catch...处理。
	当子类实现父类中方法的时候,在实现过程中如果出现“运行时异常”时，
	由于运行时异常其实已经默认抛给虚拟机(即所有方法已经默认将运行时异常抛出)，
	所以，对于运行时异常子类可以  声明  或者 try...catch...
	
	
	如果父类中要被重写的方法抛出了该异常，那么要注意，子类中抛出的异常类型要小于等于父类中异常,且如果子类声明多个异常，也要维持前面的原则。